/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

export function Planet(props) {
  const shapeContainer = useRef(null);
  const shperesContainer = useRef(null);
  const ringContainer = useRef(null);
  const { nodes, materials } = useGLTF('/models/Planet.glb');
  // Пример: как получить доступ к материалу и изменить его цвет
  useEffect(() => {
    if (materials['Material.002']) {
      // Изменяем цвет основного материала сферы
      materials['Material.002'].color.set('copper'); // Устанавливаем новый цвет
      materials['Material.002'].needsUpdate = true; // Сообщаем Three.js, что материал изменился

      // Пример: сделать его более металлическим или шероховатым (если это MeshStandardMaterial)
      // materials['Material.002'].metalness = 0.8;
      // materials['Material.002'].roughness = 0.2;

      // Пример: изменить режим наложения (blending mode)
      // materials['Material.002'].blending = THREE.AdditiveBlending; // Добавляем импорт * as THREE
      // materials['Material.002'].transparent = true;
      // materials['Material.002'].opacity = 0.7;
    }
  }, [materials]); // Зависимость от materials

  useGSAP(() => {
    const tl = gsap.timeline();
    tl.from(shapeContainer.current.position, {
      y: 5,
      duration: 3,
      ease: 'circ.out',
    });
    tl.from(
      shperesContainer.current.rotation,
      {
        x: 0,
        y: Math.PI,
        z: -Math.PI,
        duration: 10,
        ease: 'power1.inOut',
      },
      '-=25%'
    );
    tl.from(
      ringContainer.current.rotation,
      {
        x: 0.8,
        y: 0,
        z: 0,
        duration: 10,
        ease: 'power1.inOut',
      },
      '<'
    );
  }, []);

  return (
    <group ref={shapeContainer} {...props} dispose={null}>
      <group ref={shperesContainer}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={materials['Material.002']}
          rotation={[0, 0, 0.741]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere2.geometry}
          material={materials['Material.001']}
          position={[0.647, 1.03, -0.724]}
          rotation={[0, 0, 0.741]}
          scale={0.223}
        />
      </group>
      <mesh
        ref={ringContainer}
        castShadow
        receiveShadow
        geometry={nodes.Ring.geometry}
        material={materials['Material.001']}
        rotation={[-0.124, 0.123, -0.778]}
        scale={2}
      />
    </group>
  );
}

useGLTF.preload('/models/Planet.glb');
