/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

export function Planet(props) {
  const shapeContainer = useRef(null);
  const shperesContainer = useRef(null);
  const ringContainer = useRef(null);
  const { nodes, materials } = useGLTF('/models/Planet.glb');

  // Store animation context for cleanup
  const animationContext = useRef(null);

  // Material setup
  useEffect(() => {
    if (materials['Material.002']) {
      // Изменяем цвет основного материала сферы
      materials['Material.002'].color.set('copper'); // Устанавливаем новый цвет
      materials['Material.002'].needsUpdate = true; // Сообщаем Three.js, что материал изменился

      // Пример: сделать его более металлическим или шероховатым (если это MeshStandardMaterial)
      // materials['Material.002'].metalness = 0.8;
      // materials['Material.002'].roughness = 0.2;

      // Пример: изменить режим наложения (blending mode)
      // materials['Material.002'].blending = THREE.AdditiveBlending; // Добавляем импорт * as THREE
      // materials['Material.002'].transparent = true;
      // materials['Material.002'].opacity = 0.7;
    }
  }, [materials]);

  useGSAP(() => {
    // Create matchMedia context for responsive animations
    const mm = gsap.matchMedia();

    // Store the matchMedia context for cleanup
    animationContext.current = mm;

    // Desktop animations (min-width: 769px)
    mm.add('(min-width: 769px)', () => {
      const tl = gsap.timeline();

      tl.from(shapeContainer.current.position, {
        y: 5,
        duration: 3,
        ease: 'circ.out',
      });

      tl.from(
        shperesContainer.current.rotation,
        {
          x: 0,
          y: Math.PI,
          z: -Math.PI,
          duration: 10,
          ease: 'power1.inOut',
        },
        '-=25%'
      );

      tl.from(
        ringContainer.current.rotation,
        {
          x: 0.8,
          y: 0,
          z: 0,
          duration: 10,
          ease: 'power1.inOut',
        },
        '<'
      );

      // Return cleanup function for this media query
      return () => {
        tl.kill();
      };
    });

    // Mobile fallback (max-width: 768px) - minimal or no animations
    mm.add('(max-width: 768px)', () => {
      // Set static positions for mobile to avoid animation overhead
      if (shapeContainer.current) {
        gsap.set(shapeContainer.current.position, { y: 0 });
      }
      if (shperesContainer.current) {
        gsap.set(shperesContainer.current.rotation, { x: 0, y: 0, z: 0 });
      }
      if (ringContainer.current) {
        gsap.set(ringContainer.current.rotation, {
          x: -0.124,
          y: 0.123,
          z: -0.778,
        });
      }

      // Optional: Add a simple, lightweight animation for mobile
      // gsap.to(shperesContainer.current.rotation, {
      //   y: Math.PI * 2,
      //   duration: 20,
      //   ease: 'none',
      //   repeat: -1
      // });

      return () => {
        // Cleanup any mobile animations if needed
        gsap.killTweensOf([
          shapeContainer.current,
          shperesContainer.current,
          ringContainer.current,
        ]);
      };
    });

    // Cleanup function
    return () => {
      mm.kill();
    };
  }, []);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (animationContext.current) {
        animationContext.current.kill();
      }
      // Kill any remaining tweens on these elements
      gsap.killTweensOf([
        shapeContainer.current,
        shperesContainer.current,
        ringContainer.current,
      ]);
    };
  }, []);

  return (
    <group ref={shapeContainer} {...props} dispose={null}>
      <group ref={shperesContainer}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={materials['Material.002']}
          rotation={[0, 0, 0.741]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere2.geometry}
          material={materials['Material.001']}
          position={[0.647, 1.03, -0.724]}
          rotation={[0, 0, 0.741]}
          scale={0.223}
        />
      </group>
      <mesh
        ref={ringContainer}
        castShadow
        receiveShadow
        geometry={nodes.Ring.geometry}
        material={materials['Material.001']}
        rotation={[-0.124, 0.123, -0.778]}
        scale={2}
      />
    </group>
  );
}

useGLTF.preload('/models/Planet.glb');
// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useEffect, useRef } from 'react';
// import { useGLTF } from '@react-three/drei';
// import { useGSAP } from '@gsap/react';
// import gsap from 'gsap';

// export function Planet(props) {
//   const shapeContainer = useRef(null);
//   const shperesContainer = useRef(null);
//   const ringContainer = useRef(null);
//   const { nodes, materials } = useGLTF('/models/Planet.glb');
//   // Пример: как получить доступ к материалу и изменить его цвет
//   useEffect(() => {
//     if (materials['Material.002']) {
//       // Изменяем цвет основного материала сферы
//       materials['Material.002'].color.set('copper'); // Устанавливаем новый цвет
//       materials['Material.002'].needsUpdate = true; // Сообщаем Three.js, что материал изменился

//       // Пример: сделать его более металлическим или шероховатым (если это MeshStandardMaterial)
//       // materials['Material.002'].metalness = 0.8;
//       // materials['Material.002'].roughness = 0.2;

//       // Пример: изменить режим наложения (blending mode)
//       // materials['Material.002'].blending = THREE.AdditiveBlending; // Добавляем импорт * as THREE
//       // materials['Material.002'].transparent = true;
//       // materials['Material.002'].opacity = 0.7;
//     }
//   }, [materials]); // Зависимость от materials

//   useGSAP(() => {
//     const tl = gsap.timeline();
//     tl.from(shapeContainer.current.position, {
//       y: 5,
//       duration: 3,
//       ease: 'circ.out',
//     });
//     tl.from(
//       shperesContainer.current.rotation,
//       {
//         x: 0,
//         y: Math.PI,
//         z: -Math.PI,
//         duration: 10,
//         ease: 'power1.inOut',
//       },
//       '-=25%'
//     );
//     tl.from(
//       ringContainer.current.rotation,
//       {
//         x: 0.8,
//         y: 0,
//         z: 0,
//         duration: 10,
//         ease: 'power1.inOut',
//       },
//       '<'
//     );
//   }, []);

//   return (
//     <group ref={shapeContainer} {...props} dispose={null}>
//       <group ref={shperesContainer}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Sphere.geometry}
//           material={materials['Material.002']}
//           rotation={[0, 0, 0.741]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Sphere2.geometry}
//           material={materials['Material.001']}
//           position={[0.647, 1.03, -0.724]}
//           rotation={[0, 0, 0.741]}
//           scale={0.223}
//         />
//       </group>
//       <mesh
//         ref={ringContainer}
//         castShadow
//         receiveShadow
//         geometry={nodes.Ring.geometry}
//         material={materials['Material.001']}
//         rotation={[-0.124, 0.123, -0.778]}
//         scale={2}
//       />
//     </group>
//   );
// }

// useGLTF.preload('/models/Planet.glb');
